"""
ELEC5305 Project
DWT Analysis of Power Quality Disturbance Signals

This script:
1. Reads the signals generated by signal_generation.py
2. Computes Discrete Wavelet Transform (DWT) coefficients
3. Saves one DWT coefficient figure for each signal type

Required input:
    data/power_quality_signals.csv

Outputs:
    results/dwt/*.png
"""

from pathlib import Path
import os

import matplotlib.pyplot as plt
import pandas as pd
import pywt


# ============================================================
# 1. Basic Settings
# ============================================================

WAVELET = "db4"
LEVEL = 4

BASE_DIR = Path(__file__).resolve().parent
DATA_FILE = BASE_DIR / "data" / "power_quality_signals.csv"
DWT_DIR = BASE_DIR / "results" / "dwt"
OPEN_IMAGES = True

DWT_DIR.mkdir(parents=True, exist_ok=True)


def open_image(image_file):
    if OPEN_IMAGES:
        os.startfile(str(image_file))


# ============================================================
# 2. Load Signal Data
# ============================================================

def load_signals():
    """
    Load the CSV file generated by signal_generation.py.
    """
    if not DATA_FILE.exists():
        raise FileNotFoundError(
            f"\nInput file not found:\n{DATA_FILE}\n\n"
            "Please run signal_generation.py first."
        )

    df = pd.read_csv(DATA_FILE)

    signals = {}
    for column in df.columns:
        if column != "Time_s":
            display_name = column.replace("_", " ")
            signals[display_name] = df[column].to_numpy()

    return signals


# ============================================================
# 3. DWT Function
# ============================================================

def compute_dwt(signal):
    """
    Compute DWT coefficients.

    Returns:
        coeffs : [cA4, cD4, cD3, cD2, cD1] for LEVEL = 4
    """
    return pywt.wavedec(signal, WAVELET, level=LEVEL)


# ============================================================
# 4. Plot Individual DWT Coefficients
# ============================================================

def plot_individual_dwt(signals):
    """
    Generate and save one DWT coefficient figure for each signal.
    """
    coefficient_names = [f"cA{LEVEL}"] + [f"cD{i}" for i in range(LEVEL, 0, -1)]

    for name, signal in signals.items():
        coeffs = compute_dwt(signal)

        fig, axes = plt.subplots(len(coeffs), 1, figsize=(10, 8), sharex=False)

        for ax, coeff_name, coeff in zip(axes, coefficient_names, coeffs):
            ax.plot(coeff)
            ax.set_title(coeff_name)
            ax.set_ylabel("Amplitude")
            ax.grid(True)

        axes[-1].set_xlabel("Coefficient index")
        fig.suptitle(f"DWT Coefficients - {name}", fontsize=14)

        filename = name.lower().replace(" ", "_") + "_dwt.png"
        output_file = DWT_DIR / filename

        plt.tight_layout(rect=[0, 0, 1, 0.96])
        plt.savefig(output_file, dpi=300, bbox_inches="tight")
        plt.close(fig)

        print(f"Saved: {output_file}")
        open_image(output_file)


# ============================================================
# 5. Main Program
# ============================================================

def main():
    print("\n==============================================")
    print("ELEC5305 DWT Analysis")
    print("==============================================")
    print(f"Wavelet            : {WAVELET}")
    print(f"Decomposition level: {LEVEL}")
    print(f"Input file         : {DATA_FILE}")
    print("==============================================\n")

    signals = load_signals()
    print(f"Loaded {len(signals)} signal classes.\n")

    plot_individual_dwt(signals)

    print("\nDWT analysis completed successfully.")
    print(f"Results saved in: {DWT_DIR}\n")


if __name__ == "__main__":
    main()
