"""
ELEC5305 Project
FFT Analysis of Power Quality Disturbance Signals

This script:
1. Reads the signals generated by signal_generation.py
2. Computes the single-sided FFT spectrum
3. Saves one FFT figure for each signal type
4. Saves one combined FFT figure containing all six spectra

Required input:
    data/power_quality_signals.csv

Outputs:
    results/fft/*.png

Author: [Your Name]
Student ID: [Your SID]
"""

from pathlib import Path
import os

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


# ============================================================
# 1. Basic Settings
# ============================================================

FS = 6400          # Sampling frequency (Hz)
MAX_FREQ = 1000    # Maximum displayed frequency (Hz)

BASE_DIR = Path(__file__).resolve().parent
DATA_FILE = BASE_DIR / "data" / "power_quality_signals.csv"
FFT_DIR = BASE_DIR / "results" / "fft"
SAVE_OUTPUTS = True
OPEN_IMAGES = True

if SAVE_OUTPUTS:
    FFT_DIR.mkdir(parents=True, exist_ok=True)


def open_image(image_file):
    if OPEN_IMAGES:
        os.startfile(str(image_file))


# ============================================================
# 2. Load Signal Data
# ============================================================

def load_signals():
    """
    Load the CSV file generated by signal_generation.py.
    """
    if not DATA_FILE.exists():
        raise FileNotFoundError(
            f"\nInput file not found:\n{DATA_FILE}\n\n"
            "Please run signal_generation.py first."
        )

    df = pd.read_csv(DATA_FILE)

    time = df["Time_s"].to_numpy()

    signals = {}

    for column in df.columns:
        if column != "Time_s":
            display_name = column.replace("_", " ")
            signals[display_name] = df[column].to_numpy()

    return time, signals


# ============================================================
# 3. FFT Function
# ============================================================

def compute_fft(signal):
    """
    Compute a single-sided FFT amplitude spectrum.

    Returns:
        frequency : frequency axis in Hz
        amplitude : single-sided amplitude spectrum
    """
    n = len(signal)

    fft_values = np.fft.rfft(signal)

    frequency = np.fft.rfftfreq(n, d=1 / FS)

    amplitude = np.abs(fft_values) / n

    # Convert to single-sided amplitude
    if len(amplitude) > 2:
        amplitude[1:-1] = 2 * amplitude[1:-1]

    return frequency, amplitude


# ============================================================
# 4. Plot Individual FFT Spectra
# ============================================================

def plot_individual_fft(signals):
    """
    Generate and save one FFT spectrum figure for each signal.
    """
    if not SAVE_OUTPUTS:
        print("Individual FFT figure save skipped. Set SAVE_OUTPUTS = True to save files.")
        return

    for name, signal in signals.items():

        frequency, amplitude = compute_fft(signal)

        mask = frequency <= MAX_FREQ

        plt.figure(figsize=(10, 4))

        plt.plot(
            frequency[mask],
            amplitude[mask]
        )

        plt.title(f"FFT Spectrum - {name}")
        plt.xlabel("Frequency (Hz)")
        plt.ylabel("Amplitude")
        plt.grid(True)

        plt.xlim(0, MAX_FREQ)

        filename = name.lower().replace(" ", "_") + "_fft.png"
        output_file = FFT_DIR / filename

        plt.tight_layout()
        plt.savefig(output_file, dpi=300, bbox_inches="tight")
        plt.close()

        print(f"Saved: {output_file}")
        open_image(output_file)


# ============================================================
# 5. Plot Combined FFT Figure
# ============================================================

def plot_all_fft(signals):
    """
    Generate one figure containing FFT spectra for all six signals.
    """
    return

    fig, axes = plt.subplots(3, 2, figsize=(12, 10))

    axes = axes.flatten()

    for ax, (name, signal) in zip(axes, signals.items()):

        frequency, amplitude = compute_fft(signal)

        mask = frequency <= MAX_FREQ

        ax.plot(
            frequency[mask],
            amplitude[mask]
        )

        ax.set_title(name)
        ax.set_xlabel("Frequency (Hz)")
        ax.set_ylabel("Amplitude")
        ax.set_xlim(0, MAX_FREQ)
        ax.grid(True)

    fig.suptitle(
        "FFT Spectra of Six Power Quality Signals",
        fontsize=14
    )

    plt.tight_layout(rect=[0, 0, 1, 0.97])

    if SAVE_OUTPUTS:
        output_file = FFT_DIR / "six_fft_spectra.png"
        plt.savefig(
            output_file,
            dpi=300,
            bbox_inches="tight"
        )
        print(f"Combined FFT figure saved to: {output_file}")

    plt.close(fig)


# ============================================================
# 6. Print Dominant Frequency Components
# ============================================================

def print_dominant_frequencies(signals, number_of_peaks=5):
    """
    Print the strongest FFT frequency components for each signal.
    """
    print("\n==============================================")
    print("Dominant Frequency Components")
    print("==============================================")

    for name, signal in signals.items():

        frequency, amplitude = compute_fft(signal)

        # Ignore DC component at 0 Hz
        valid = frequency > 0

        freq_valid = frequency[valid]
        amp_valid = amplitude[valid]

        indices = np.argsort(amp_valid)[-number_of_peaks:][::-1]

        print(f"\n{name}:")

        for index in indices:
            print(
                f"  {freq_valid[index]:8.2f} Hz"
                f"    amplitude = {amp_valid[index]:.4f}"
            )

    print("\n==============================================\n")


# ============================================================
# 7. Save FFT Data to CSV
# ============================================================

def save_fft_data(signals):
    """
    Save FFT frequency and amplitude data to CSV files.
    """
    if not SAVE_OUTPUTS:
        print("FFT data save skipped. Set SAVE_OUTPUTS = True to save files.")
        return

    for name, signal in signals.items():

        frequency, amplitude = compute_fft(signal)

        output_df = pd.DataFrame({
            "Frequency_Hz": frequency,
            "Amplitude": amplitude
        })

        filename = name.lower().replace(" ", "_") + "_fft.csv"
        output_file = FFT_DIR / filename

        output_df.to_csv(output_file, index=False)


# ============================================================
# 8. Main Program
# ============================================================

def main():

    print("\n==============================================")
    print("ELEC5305 FFT Analysis")
    print("==============================================")
    print(f"Sampling frequency : {FS} Hz")
    print(f"Display range      : 0 - {MAX_FREQ} Hz")
    print(f"Input file         : {DATA_FILE}")
    print("==============================================\n")

    time, signals = load_signals()

    print(f"Loaded {len(signals)} signal classes.")
    print(f"Samples per signal: {len(time)}\n")

    print_dominant_frequencies(signals)

    save_fft_data(signals)

    plot_individual_fft(signals)

    plot_all_fft(signals)

    print("\nFFT analysis completed successfully.")
    if SAVE_OUTPUTS:
        print(f"Results saved in: {FFT_DIR}\n")


if __name__ == "__main__":
    main()
