"""
ELEC5305 Project
STFT Analysis of Power Quality Disturbance Signals

This script:
1. Reads the signals generated by signal_generation.py
2. Computes the Short-Time Fourier Transform (STFT)
3. Saves one STFT spectrogram figure for each signal type

Required input:
    data/power_quality_signals.csv

Outputs:
    results/stft/*.png
"""

from pathlib import Path
import os

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.signal import stft


# ============================================================
# 1. Basic Settings
# ============================================================

FS = 6400
MAX_FREQ = 1000
WINDOW_LENGTH = 256
OVERLAP = 192

BASE_DIR = Path(__file__).resolve().parent
DATA_FILE = BASE_DIR / "data" / "power_quality_signals.csv"
STFT_DIR = BASE_DIR / "results" / "stft"
OPEN_IMAGES = True

STFT_DIR.mkdir(parents=True, exist_ok=True)


def open_image(image_file):
    if OPEN_IMAGES:
        os.startfile(str(image_file))


# ============================================================
# 2. Load Signal Data
# ============================================================

def load_signals():
    """
    Load the CSV file generated by signal_generation.py.
    """
    if not DATA_FILE.exists():
        raise FileNotFoundError(
            f"\nInput file not found:\n{DATA_FILE}\n\n"
            "Please run signal_generation.py first."
        )

    df = pd.read_csv(DATA_FILE)

    signals = {}
    for column in df.columns:
        if column != "Time_s":
            display_name = column.replace("_", " ")
            signals[display_name] = df[column].to_numpy()

    return signals


# ============================================================
# 3. STFT Function
# ============================================================

def compute_stft(signal):
    """
    Compute STFT magnitude in dB.

    Returns:
        time : STFT time axis in seconds
        frequency : frequency axis in Hz
        magnitude_db : magnitude spectrogram in dB
    """
    frequency, time, values = stft(
        signal,
        fs=FS,
        window="hann",
        nperseg=WINDOW_LENGTH,
        noverlap=OVERLAP,
        boundary=None,
    )

    magnitude = np.abs(values)
    magnitude_db = 20 * np.log10(magnitude + 1e-12)

    return time, frequency, magnitude_db


# ============================================================
# 4. Plot Individual STFT Spectrograms
# ============================================================

def plot_individual_stft(signals):
    """
    Generate and save one STFT spectrogram figure for each signal.
    """
    for name, signal in signals.items():
        time, frequency, magnitude_db = compute_stft(signal)

        mask = frequency <= MAX_FREQ

        plt.figure(figsize=(10, 4))
        plt.pcolormesh(
            time,
            frequency[mask],
            magnitude_db[mask, :],
            shading="gouraud",
            cmap="viridis",
        )
        plt.title(f"STFT Spectrogram - {name}")
        plt.xlabel("Time (s)")
        plt.ylabel("Frequency (Hz)")
        plt.ylim(0, MAX_FREQ)
        plt.colorbar(label="Magnitude (dB)")

        filename = name.lower().replace(" ", "_") + "_stft.png"
        output_file = STFT_DIR / filename

        plt.tight_layout()
        plt.savefig(output_file, dpi=300, bbox_inches="tight")
        plt.close()

        print(f"Saved: {output_file}")
        open_image(output_file)


# ============================================================
# 5. Main Program
# ============================================================

def main():
    print("\n==============================================")
    print("ELEC5305 STFT Analysis")
    print("==============================================")
    print(f"Sampling frequency : {FS} Hz")
    print(f"Display range      : 0 - {MAX_FREQ} Hz")
    print(f"Input file         : {DATA_FILE}")
    print("==============================================\n")

    signals = load_signals()
    print(f"Loaded {len(signals)} signal classes.\n")

    plot_individual_stft(signals)

    print("\nSTFT analysis completed successfully.")
    print(f"Results saved in: {STFT_DIR}\n")


if __name__ == "__main__":
    main()
